### ISSUE TITLE
Call nk "seed" "secret" instead

### ISSUE THREAD

**Issue by JensRantil** [nats-io/nats.docs#10]
I read https://docs.nats.io/nats-tools/nk#generating-nkeys-and-configuring-the-server and it says

> The first output line starts with the letter S for Seed.

From a mnemonics standpoint, it might be easier to remember "S" for "secret" as that's what it really is and it's crucial, from a security standpoint, that users `nk` don't send around the wrong token. How about changing to that?

**Comment by derekcollison** [comment]
Ed25519 have both private keys and a seed, one is 64 bytes and the other 32bytes. The 32byte entity is referred to as the seed, hence our doing the same.

https://godoc.org/golang.org/x/crypto/ed25519

We do try to say that the seed is also a secret.
