### ISSUE TITLE
"Creating an Operator" documentation needs updating

### ISSUE THREAD

**Issue by JensRantil** [nats-io/nats.docs#12]
https://docs.nats.io/nats-tools/nsc/nsc#creating-an-operator claims `nsc add operator -n Test` output should look like
```
Generated operator key - private key stored “~/.nkeys/Test/Test.nk”
Success! - added operator "Test"
```
but it looked like
```
$ nsc add operator -n Test
[ OK ] generated and stored operator key "OAXE7CKC44VD2ENMV5G5M7FH4OWSEVWF2NC3AYWLIGHKYZ6KHL46RGWF"
[ OK ] added operator "Test"
```
.

Also, `~/.nkeys/Test/Test.nk` doesn't exist on my machine:
```
$ tree ~/.nkeys
/Users/jrantil/.nkeys
├── creds
└── keys
    └── O
        └── AX
            └── OAXE7CKC44VD2ENMV5G5M7FH4OWSEVWF2NC3AYWLIGHKYZ6KHL46RGWF.nk

4 directories, 1 file
```

**Comment by JensRantil** [comment]
Also, `nats-account-server -nsc ~/.nsc/nats/Test` can't work as the directory doesn't exist.

**Comment by aricart** [comment]
> Also, `~/.nkeys/Test/Test.nk` doesn't exist on my machine:

can you do `nsc env` - your nkeys dir is likely in a non-default place, so the documentation won't jive with that.
