### ISSUE TITLE
build failed: unknown block tag: tabs

### ISSUE THREAD

**Issue by jinq0123** [nats-io/nats.docs#122]
```
# make
gitbook install
info: installing 5 plugins using npm@3.9.2
...
info: install plugin "edit-link" (*) from NPM with version 2.0.2
info: >> plugin "edit-link" installed with success
sed -i.bak 's/fa-edit/fa-github/g' node_modules/gitbook-plugin-edit-link/book/plugin.js
go run _tools/examplecompiler/main.go -o _examples -r _tools/examplecompiler/example_repos.json -t _tools/examplecompiler/example_template.tmp
Working directory created: "/tmp/site_examples713379379"
Insuring output folder: _examples
Downloading repo: "https://github.com/nats-io/java-nats-examples.git"
Searching for examples in: "/tmp/site_examples713379379/repos/java-nats-examples"
...
Formatting examples
        Formatted "connect_tls" to "_examples/connect_tls.html"
...
        Formatted "subscribe_sync" to "_examples/subscribe_sync.html"
rm -rf _.docs
gitbook build . _docs
info: 12 plugins are installed
info: 9 explicitly listed
info: loading plugin "prism"... OK
info: loading plugin "include-html"... OK
info: loading plugin "toggle-chapters"... OK
info: loading plugin "anchors"... OK
info: loading plugin "edit-link"... OK
info: loading plugin "search"... OK
info: loading plugin "lunr"... OK
info: loading plugin "fontsettings"... OK
info: loading plugin "theme-default"... OK
info: found 175 pages
info: found 36 asset files
warn: "options" property is deprecated, use config.get(key) instead
warn: "options.generator" property is deprecated, use "output.name" instead
error: error while generating page "developing-with-nats/connecting/specific_server.md":

Template render error: (/nats.docs/developing-with-nats/connecting/specific_server.md) [Line 9, Column 2]
  unknown block tag: tabs
Makefile:2: recipe for target 'build' failed
make: *** [build] Error 1
#
```

**Comment by jinq0123** [comment]
```
# gitbook --version
CLI version: 2.3.2
GitBook version: 3.2.3
#
```

**Comment by gcolliso** [comment]
@jinq0123 our docs are now hosted by Gitbook and I don't believe it will build outside of their environment. Our previous build was on Gitbook legacy. Is there something you are trying to do or information you need?

**Comment by jinq0123** [comment]
I am trying to run a local server or to generate a pdf.

**Comment by gcolliso** [comment]
@jinq0123 there is no ability with the current version of Gitbook to run a local version. There is a feature request into Gitbook for this to be added. I also see they have added a Beta export to PDF feature, but it seems it's not working for our site. I will continue to look into this though as it would be a feature we'd like to give our users.

**Comment by gcolliso** [comment]
@jinq0123 I see that the option to Export to PDF has been enabled on [docs.nats.io](https://docs.nats.io). You can choose to export a page or the site using the Export to PDF option in the right-hand side mini-menu.

**Comment by jinq0123** [comment]
I deleted all "{% ".

**Comment by williamstein** [comment]
>  I see that the option to Export to PDF has been enabled on [docs.nats.io](https://docs.nats.io/). You can choose to export a page or the site using the Export to PDF option in the right-hand side mini-menu.

Exporting more than a few pages crashes every browser I've tried (Chrome, Safari, Firefox).

> there is no ability with the current version of Gitbook to run a local version. 

You should maybe remove or modify https://github.com/nats-io/nats.docs/blob/master/building_the_book.md

**Is there any way to get a linear version of the docs that one can read offline in order?**
