### ISSUE TITLE
Account Server - Curl accounts management

### ISSUE THREAD

**Issue by dmitrydiavita** [nats-io/nats.docs#140]
Hi, you have a very little describing of how to use curl to add/update accounts with api here https://docs.nats.io/nats-tools/nas/dir_store#using-curl-to-add-or-update-accounts

Have any detailed explaining of how to manage account server (add accounts, add users or change users permissions in account, import or export topics and etc..) with api (without manual using of cli) ?

**Comment by bruth** [comment]
The NATS account server has since been deprecated. The current recommended approach is to use the built-in NATS resolver: https://docs.nats.io/running-a-nats-service/configuration/securing_nats/auth_intro/jwt/resolver
