### ISSUE TITLE
Sending Messages in C/C++

### ISSUE THREAD

**Issue by kkyuri0419** [nats-io/nats.docs#144]
I am a beginner and wants to see the examples of sending messages in C/C++. But the docs only provides them in Go, Java, JavaScript,Python, Ruby,TypeScript. 
Where can I find sample codes for sending messages to NATS server in C/C++ languages??
Thank you very much in advance!

**Comment by gcolliso** [comment]
@kkyuri0419 We will add the C examples to the docs but in the meantime, you can find examples in the NATS C Client Repo https://github.com/nats-io/nats.c#getting-started

**Comment by gcolliso** [comment]
C examples added to docs.nats.io
