### ISSUE TITLE
Concurrent clients?

### ISSUE THREAD

**Issue by oliverhausler** [nats-io/nats.docs#180]
Exists in FAQ:

- Is there a message size limitation in NATS?
- Does NATS impose any limits on the # of subjects?

Missing from FAQ:

- How many clients can connect simultaneously?

---

I tried to find a response to this question and couldn't find anywhere. Is there a maximum number of concurrent clients? What does it depend on? Is the clients list partitioned, e.g. does it grow when a NATS server is added?

You may want to add this to your FAQs.

**Comment by gcolliso** [comment]
@oliverhausler we have added an entry to the FAQ to address your question. Please advise if you have any questions.

**Comment by oliverhausler** [comment]
@gcolliso Thank you, appreciate it.
