### ISSUE TITLE
Unable to install mkpasswd like in documentation

### ISSUE THREAD

**Issue by moleksyuk** [nats-io/nats.docs#183]
Hi guys,

I'm trying to install `mkpasswd` from [this documentation](https://docs.nats.io/nats-tools/mkpasswd#installing-mkpasswd).

**Issue No.1** - Wrong symbol in command
Copy button copies content `> go get github.com/nats-io/nats-server/util/mkpasswd` with starting `>`. It makes command invalid and getting error: `-bash: go: Is a directory`

**Issue No.2** - Unable to install mkpasswd

**Steps to reproduce:**
1. Install **go**: `sudo snap install go --classic`
2. Install **mkpasswd**: `go get github.com/nats-io/nats-server/util/mkpasswd`

Actual: getting error
```
~$ go get github.com/nats-io/nats-server/util/mkpasswd
package github.com/nats-io/nats-server/util/mkpasswd: build constraints exclude all Go files in /home/ubuntu/go/src/github.com/nats-io/nats-server/util/mkpasswd
```

Expected: mkpasswd is installed.

OS: 
```Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```
Go: 
`go version go1.15.6 linux/amd64`

Go env:
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ubuntu/.cache/go-build"
GOENV="/home/ubuntu/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/ubuntu/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ubuntu/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/snap/go/6745"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/snap/go/6745/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build471404296=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by gcolliso** [comment]
@wallyqs, @variadico could you take a look at this issue, please?

**Comment by variadico** [comment]
Sure thing, @gcolliso. :+1:

**Comment by variadico** [comment]
Whoops, actually, `go get`ing `mkpasswd`  still fails. Gotta settle https://github.com/nats-io/nats-server/pull/1841 before `go get` works again.

**Comment by variadico** [comment]
Okay, so looks like we're going to migrate the functionality of `mkpasswd` into our all-in-one tool: [nats-io/natscli](https://github.com/nats-io/natscli).

```
$ nats server passwd
? Enter password [? for help] **********************
? Reenter password [? for help] **********************

$2a$11$uMiop3/RsLSrMs3e1U6crurxRzRI8hYgE/Rtmii5yeBxclpG4CF8q
```

For now, you'll have to manually install [nats-io/natscli](https://github.com/nats-io/natscli) if you want to use this functionality, but I bet the next release of the cli will include this.

**Comment by variadico** [comment]
All right. The changes to update the documentation have been submitted. We should see the new instructions on how to generate bcrypted passwords reflected on https://docs.nats.io/ soon.
