### ISSUE TITLE
Deployment apiVersion issue

### ISSUE THREAD

**Issue by karankumarshreds** [nats-io/nats.docs#211]
Followed the [docs](https://docs.nats.io/nats-on-kubernetes/stan-ft-k8s-aws)

It gives an error 

```
no matches for kind "Deployment" in version "extensions/v1beta1"
```

Same doesn't work with **apps/v1**, which gives an error saying **selector** missing.

Please update

**Comment by gcolliso** [comment]
@wallyqs could you take a look at this one?

**Comment by karankumarshreds** [comment]
@gcolliso , I've opened a PR for this with a solution. 
The solution worked for the latest version of EKS.

**Comment by wallyqs** [comment]
Thanks again @karankumarshredsfor the contribution
