### ISSUE TITLE
Clarification about MaxInFlight

### ISSUE THREAD

**Issue by uncaughtgregory** [nats-io/nats.docs#256]
For NATS Streaming, when the number of pending messages reach the MaxInFlight,

> NATS Streaming will suspend delivery of messages to this subscription until the number of unacknowledged messages falls below the specified limit

My question is when the `MaxInFlight` limit is reached, will the producer be blocked, i.e. can the producer still publish to the channel?

**Comment by gcolliso** [comment]
@kozlovic could you review and clarify for @uncaughtgregory ?

**Comment by uncaughtgregory** [comment]
@kozlovic Please take a look!

**Comment by kozlovic** [comment]
Sorry I missed the original notification. The MaxInflight as described is an option of the Subscription, and the server suspends delivery to the subscription.
The publisher is unaffected. The publisher is blocked base on `MaxPubAcksInFlight` that is described just above in the doc your reference.

**Comment by uncaughtgregory** [comment]
Thanks for confirming! @kozlovic

**Comment by uncaughtgregory** [comment]
I have a follow-up question:
When channel `MaxInflight` is reached, the NATS server will stop delivering new messages to the subscriber. When that happens, will the NATS server also stop `ack` new messages published to the server?

**Comment by kozlovic** [comment]
First, we are talking about NATS Streaming server, not NATS Server :-)

Again, MaxInflight affects only the streaming subscription, nothing else. In NATS in general (streaming and core), publishers and subscribers are de-coupled.

So to answer your question: no, the server will not stop ack'ing published message when a subscriptions has reached its MaxInflight messages.
