### ISSUE TITLE
Update NATS Protocol

### ISSUE THREAD

**Issue by gcolliso** [nats-io/nats.docs#257]
Need to get https://docs.nats.io/nats-protocol/nats-protocol to represent NATS 2.2 features...

 - miss messges for headers, like HPUB.
 - no responders
 - is the INFO payload JSON? need to clarify

**Comment by gcolliso** [comment]
@ColinSullivan1 could you update the NATS protocol doc to reflect the new 2.2 features?

**Comment by samueleaton** [comment]
bump. doing work on a client and this would be helpful.

**Comment by gcolliso** [comment]
@ColinSullivan1, @jnmoyne This issue is still outstanding. Who would be the right person to update the docs?

**Comment by ColinSullivan1** [comment]
We'll get someone to take a look after we wrap up a few other things in development. In the meantime, consider [nats.go](https://github.com/nats-io/nats.go) our canonical client which can be used as a reference.

**Comment by bruth** [comment]
@tbeets Updated the doc in #501 and a remaining call-out about JSON in #518
