### ISSUE TITLE
Missing diagram in Jetstream docs

### ISSUE THREAD

**Issue by MerzMax** [nats-io/nats.docs#276]
In the second paragraph of the [Jetstream/Concept/Streams](https://docs.nats.io/jetstream/concepts/streams) documentation you mention a diagram that is missing.

**Comment by gcolliso** [comment]
Thanks for the notification @MerzMax. That paragraph references the diagram from the previous page. We had split the Streams section from the main Concepts section and forgot to duplicate the diagram. Fixed #277
