### ISSUE TITLE
Mistake in guest post

### ISSUE THREAD

**Issue by StarpTech** [nats-io/nats.docs#29]
> The queue subscriber enables multiple clients to subscribe to the same stream with the same “queue name” and **messages will be distributed to each member of the queue group.**
https://nats.io/blog/use-cases-for-persistent-logs-with-nats-streaming/

This is not correct. Queue groups are designed to load balance traffic.

**Comment by ColinSullivan1** [comment]
@StarpTech , thank you for raising this.  This was a guest post, and we don't like altering posts without the author's permission.  I do think this can be read accurately - but do admit there's some ambiguity without the the first sentence. Messages are distributed among members of the group.  @bruth, wdyt?

**Comment by bruth** [comment]
That does read a bit odd now that you bring it up. This is what the NATS docs states for queue groups:

> NATS provides a built-in load balancing feature called distributed queues. Using queue subscribers will balance message delivery across a group of subscribers which can be used to provide application fault tolerance and scale workload processing.

Maybe it should say "messages will be load balanced across members of the queue group"?

**Comment by StarpTech** [comment]
@bruth The whole sentence makes sense for me because of the keyword `load balancing` but in the guest post, there is no reference about it.

**Comment by bruth** [comment]
@StarpTech Sure, I am suggesting that we change what I wrote to this:

> The queue subscriber enables multiple clients to subscribe to the same stream with the same “queue name” and messages will be **load balanced across members of the queue group**.

**Comment by bruth** [comment]
@ColinSullivan1 You have my permission to change the text to the above. 😉

**Comment by gcolliso** [comment]
Thanks @ColinSullivan1 , @bruth and @StarpTech I will make the update.

**Comment by gcolliso** [comment]
fixed with PR#532 [https://github.com/nats-io/nats-site/pull/532](https://github.com/nats-io/nats-site/pull/532)
