### ISSUE TITLE
NATS Account Server obsolete?

### ISSUE THREAD

**Issue by coder543** [nats-io/nats.docs#305]
From the [2.2 release notes](https://docs.nats.io/whats_new_22#security-and-simplified-account-management), it sounds like the `nats-account-server` is obsolete, but the [doc page for nats-account-server](https://docs.nats.io/nats-tools/nas) makes no mention of this, so I was initially confused into believing it was still needed? I could be misreading something.

**Comment by jnmoyne** [comment]
The documentation has been updated to reflect the NATS Resolver being preferred and standalone account server being deprecated to legacy as part of https://github.com/nats-io/nats.docs/pull/326
