### ISSUE TITLE
Missing content in JetStream Clustering docs

### ISSUE THREAD

**Issue by denis-osipov** [nats-io/nats.docs#329]
Hi.

It looks like content from [/running-a-nats-service/configuration/clustering/jetstream_clustering](https://github.com/nats-io/nats.docs/tree/master/running-a-nats-service/configuration/clustering/jetstream_clustering) does not apper in [JetStream Clustering docs](https://docs.nats.io/running-a-nats-service/configuration/clustering/jetstream-clustering).

![image](https://user-images.githubusercontent.com/24683226/142978490-5e24832b-2e62-4b40-93bf-6343798b781c.png)
![image](https://user-images.githubusercontent.com/24683226/142978532-08f275cb-ce68-4dd5-8f33-68b197c2dd12.png)

**Comment by gcolliso** [comment]
@denis-osipov thank you for the report. I have made the appropriate updates.
