### ISSUE TITLE
nats  Persistence: link pointing to a wrong route in the documentation

### ISSUE THREAD

**Issue by AbdelouahabMbarki** [nats-io/nats.docs#348]
Hi everyone 
i found that the **SQL Store**  link in This  documentation page [persistence]( https://docs.nats.io/legacy/stan/changes/configuring/persistence) is taking to this route https://docs.nats.io/legacy/stan/changes/configuring/persistence instead of this https://docs.nats.io/legacy/stan/changes/configuring/persistence/sql_store
![image](https://user-images.githubusercontent.com/52507296/145379617-7a50a3dc-2d75-4c2c-ad5e-9df3edcf965d.png)

**Comment by gcolliso** [comment]
fixed in PR#349 - thanks for the alert @AbdelouahabMbarki
