### ISSUE TITLE
Move K8S section to top level

### ISSUE THREAD

**Issue by wallyqs** [nats-io/nats.docs#359]
Right now the Kubernetes section is a bit hidden, I think a good place to add it would be within the following two items:

![image](https://user-images.githubusercontent.com/26195/149202200-f27d5af8-ce46-49d9-a74e-039379b74a4c.png)

Then add there this collection of docs:

https://github.com/nats-io/nats.docs/tree/master/running-a-nats-service/nats-on-kubernetes

**Comment by jnmoyne** [comment]
It is already right inside the first one (Installing, running, deploying)
<img width="303" alt="Screen Shot 2022-01-13 at 17 01 47" src="https://user-images.githubusercontent.com/7819096/149433357-2513ec0b-5016-4524-94a1-dc3ff791ecf4.png">

**Comment by wallyqs** [comment]
Let's bump it up to the same level as `Running a NATS Service` section, something like...

![image](https://user-images.githubusercontent.com/26195/149461281-de6e2f7e-21ac-4991-94ee-510115ccc7c8.png)

**Comment by jnmoyne** [comment]
Ok how about I bring it up two levels (it would be always visible in the summary pane not inside something you need to expand) so top level inside "Running a NATS Service" section? I also propose to move the docker section as well as I think they should both be at the same level.

**Comment by wallyqs** [comment]
That sounds fine

**Comment by jnmoyne** [comment]
See https://github.com/nats-io/nats.docs/pull/361
