### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by kantum** [nats-io/nats.docs#363]
Hello, just starting to learn about nats but the telnet demo is giving me an error before I can play with it :crying_cat_face: 

I followed [these instructions](https://github.com/nats-io/nats.docs/blob/master/reference/nats-protocol/nats-protocol-demo.md)

When I run `telnet demo.nats.io 4222` I get:
```
Trying 145.40.102.131...
Connected to demo.nats.io.
Escape character is '^]'.
INFO {"server_id":"NBRTLDOI4STEAGVQNG445CWVBGODOTFFGWKOLPGAAVBG3CCFPTLHEWIP","server_name":"us-central-nats-demo","version":"2.7.0","proto":1,"go":"go1.17.6","host":"0.0.0.0","port":4222,"headers":true,"auth_required":true,"tls_available":true,"max_payload":1048576,"jetstream":true,"client_id":515006,"client_ip":"x.x.x.x","nonce":"OU4jM5xnTrZC1iE"}
```
then after some time:
```
-ERR 'Authentication Timeout'
Connection closed by foreign host.
```

It seems like someone added some authentication mechanism, I think it has to be explained in the demo documentation to avoid frustration.

Regards

**Comment by gcolliso** [comment]
Thank you @kantum - this is a known issue because of the new setup it forces a CONNECT proto now. We are working on a fix.

**Comment by kantum** [comment]
Can't wait

**Comment by gcolliso** [comment]
@kantum We have made an update to the demo server. Please try the telnet to demo.nats.io and let me know if you are still experiencing the same issue.

**Comment by kantum** [comment]
It's seams to be the intended behaviour, it stops consistently within 12 seconds:

```
time telnet demo.nats.io 4222
...
telnet demo.nats.io 4222  0.02s user 0.01s system 0% cpu 11.371 total
```
I was excepting the connection to stay open much longer, as the doc later says: _If you leave your telnet session open for a few minutes, you may notice that your clients receives ping requests from the server._

Anyway, it works if I run any command within 12 seconds!

**Comment by bruth** [comment]
Hi @kantum, I opened #580 to indicate the need to send the `CONNECT {}` message to confirm the client connection, as well as simply the tutorial. This will correctly maintain an open connection beyond 12 seconds.

Please leave a connect on the PR to further review, thanks!
