### ISSUE TITLE
Typo in log_size_limit

### ISSUE THREAD

**Issue by stayleen** [nats-io/nats.docs#427]
The description of logging setting `log_size_limit` gives `logfile_size_limit` as the setting name in the description of [logging settings](https://docs.nats.io/running-a-nats-service/configuration/logging) This does not match the actual implementation in the code.

This typo is repeated in section **Log Rotation**

**Comment by bruth** [comment]
Hi @stayleen, many of the config options have aliases. As you can see [here](https://github.com/nats-io/nats-server/blob/57daedafa849a371ee89362edd4fe78157340507/server/opts.go#L923), both names are supported.
