### ISSUE TITLE
Document supported hardware architectures

### ISSUE THREAD

**Issue by gcolliso** [nats-io/nats.docs#443]
[zamazan4ik](https://github.com/zamazan4ik)
Moving nats-server issue [#3200](https://github.com/nats-io/nats-server/issues/3200) to proper repo 

Hi!

I have checked the documentation but did not find any word about supported architectures.

Could you please put the information about supported architectures to the documentation please? E.e. about supported architectures for different operating systems, some specific requirements to the supported instructions, if you have any (e.g. maybe AVX is required - I do not know).

This kind of information is important for the end-users.

Thanks in advance!

**Comment by bruth** [comment]
@zamazan4ik Added a section here: https://docs.nats.io/running-a-nats-service/introduction/installation#supported-operating-systems-and-architectures

**Comment by zamazan4ik** [comment]
Thanks! Just didn't know that Windows works on arm6 :)

**Comment by bruth** [comment]
I don't suspect the support OSes and archs will change often, but all the builds are published as [assets for each release](https://github.com/nats-io/nats-server/releases/tag/v2.9.0), just FYI.
