### ISSUE TITLE
Consider applying for DocuSearch for improved search

### ISSUE THREAD

**Issue by bruth** [nats-io/nats.docs#445]
DocuSearch is powered by [Algolia](https://www.algolia.com). Per the [DocuSearch docs](https://docsearch.algolia.com/docs/who-can-apply):

> We built DocSearch from the ground up with the idea of improving search on large technical documentations. For this reason, we are offering a free hosting version to all online technical documentations of open-source projects and technical blogs.

Integration requires a snippet of JavaScript to be included in the site. Sites can [apply here](https://docsearch.algolia.com/apply).

**Comment by gcolliso** [comment]
@bruth We use GitBook for our docs and they have their own built-in search. I don't believe we have the ability to change or add a new search.

**Comment by gcolliso** [comment]
You are not the first to indicate the search needs improvement. FWIW, we do use Algolia for nats.site/blog.

When reviewing plugins for GitBook, understand we are using the hosted version and no additional plugins are allowed. Some of the code in this repo may still be from the legacy version we used previously.

We are always looking for improved documentation apps/ideas so if you have any suggestions, let'em fly! 😃

**Comment by bruth** [comment]
Ah ok, good to know about the plugins and that you are already using Algolia for the blog. I will ponder on this a bit more, thanks!
