### ISSUE TITLE
Remove extra Spaces in file docs/developer/tutorials/intro.html.

### ISSUE THREAD

**Issue by asvindraRajpoot** [nats-io/nats.docs#448]
Extra spaces does not look good in file , it should be formatted.

**Comment by gcolliso** [comment]
@asvindraRajpoot could you specify the URL as I'm not finding the file you are referring to.

**Comment by gcolliso** [comment]
That file is no longer applicable in our production docs - are you reviewing docs at https://docs.nats.io?

**Comment by asvindraRajpoot** [comment]
ok Then we can close this issue.
