### ISSUE TITLE
[DOCS] Broken link in docs for NATS Account Server

### ISSUE THREAD

**Issue by karuppiah7890** [nats-io/nats.docs#521]
The NATS Account Server link at https://github.com/nats-io/nats.docs/blob/master/using-nats/nats-tools/readme.md is broken. The broken link / 404 link is - https://github.com/nats-io/nats.docs/blob/master/using-nats/nats-tools/nats-tools/nas/README.md

**Comment by gcolliso** [comment]
@jnmoyne nas was moved to legacy - should the home page of NATS Tools remove the reference to NATS Account Server or should the link go to the legacy info, or is there another page for NATS Account Server?

**Comment by jnmoyne** [comment]
The link should be updated to point to the NATS Account Server section in legacy (see https://github.com/nats-io/nats.docs/pull/522)
