### ISSUE TITLE
Broken link in TLS documentation

### ISSUE THREAD

**Issue by zamazan4ik** [nats-io/nats.docs#531]
Hi!

There is a broken link here: https://docs.nats.io/running-a-nats-service/configuration/securing_nats/tls#nats.rs

The link to nowhere. Could you please fix the link?

Thanks in advance!

**Comment by gcolliso** [comment]
fixed in PR #532

**Comment by zamazan4ik** [comment]
@gcolliso Is it really fixed? I still have an error:
<img width="1322" alt="image" src="https://user-images.githubusercontent.com/7355383/201195486-8b37fd34-3a3b-4a3e-9d2a-42f5c939bc1c.png">

**Comment by gcolliso** [comment]
Ugh - my apologies. Updated the full URL. You should be g2g now.

**Comment by zamazan4ik** [comment]
Yeah, now it works - thanks!
