### ISSUE TITLE
Broken link reference in doc

### ISSUE THREAD

**Issue by karuppiah7890** [nats-io/nats.docs#534]
Doc - https://docs.nats.io/running-a-nats-service/introduction/running#configuration-file , https://github.com/nats-io/nats.docs/blob/master/running-a-nats-service/running/README.md#configuration-file

Broken Link is in the `Configuration File` section for the text [`containerized NATS is available here`](https://github.com/nats-io/nats.docs/blob/master/running-a-nats-service/nats_docker). - https://github.com/nats-io/nats.docs/blob/master/running-a-nats-service/nats_docker/README.md

**Comment by gcolliso** [comment]
fixed in PR #536
