### ISSUE TITLE
Client Protocol Field Documentation

### ISSUE THREAD

**Issue by samisagit** [nats-io/nats.docs#570]
The client protocol documentation is lacking detail for certain fields. Type information, and optionality would be very useful to have at a glance.

https://docs.nats.io/reference/reference-protocols/nats-protocol#connect for e.g. shows a list of fields, some of which are explicitly marked as optional, some with a dependency of `if auth_required is set` (which also begs the question, what if it's set to false?) and some without any indication. However in the example messages, there are fields missing that aren't explicitly called out as optional 

e.g. 

```
CONNECT {"verbose":false,"pedantic":false,"tls_required":false,"name":"","lang":"go","version":"1.2.2","protocol":1}␍␊
```

is missing the field `jwt` but this field is not marked as optional.

Suggest a table format for such fields as below or similar

|name|description|type|required|
|-------|----|---------|------------|
| jwt |The JWT that identifies a user permissions and account.| string | false|
| user |client name| string | if `auth_required` is true |

I'm happy to submit a PR if a change is deemed necessary.

**Comment by gcolliso** [comment]
Hello @samisagit 👋 
If you would submit a PR, we would greatly appreciate it. Thank you for the offer!

**Comment by samisagit** [comment]
Submitted the PR above, would be great to get some eyes on the type/required fields in the tables, since they're mostly inferred. All the descriptions are copied from the original content, with a few minor edits where the information was redundant due to the new table fields.
