### ISSUE TITLE
Standardize installation methods for Windows

### ISSUE THREAD

**Issue by mesakomarevich** [nats-io/nats.docs#586]
## Problem
The Windows installation instructions and installation methods for several NATS projects are inconsistent or out of date.

### NATS Server
When reading through [Installing a NATS Server > Installing via a Package Manager](https://docs.nats.io/running-a-nats-service/introduction/installation#installing-via-a-package-manager), the instructions for Windows tell us to install via [Chocolatey](https://community.chocolatey.org/packages/nats-server), but neglects to mention that you can also install via [Scoop](https://github.com/nats-io/nats-server/issues/2063). Further to this issue, the [version of NATS Server available on Chocolately](https://community.chocolatey.org/packages/nats-server) was last updated in 2019, but the version available on Scoop is up to date

### NATS CLI
The docs for [installing the NATS CLI](https://docs.nats.io/using-nats/nats-tools/nats_cli#installing-nats) don't even mention installation on Windows. However, the NATS CLI can be installed from the [Scoop Extras bucket](https://github.com/ScoopInstaller/Extras/pull/10250), but cannot be installed on Chocolatey. 

### Chocolatey
There seem to be two good options here:
- Remove the references to installing the NATS Server through Chocolatey and officially depricate or remove the package, if possible.
- Update the version of NATS Server available through Chocolatey and add the ability to install the NATS CLI through Chocolatey.

### Scoop
Add installation instructions for Scoop to both the NATS Server and NATS CLI docs.

### General package management
I am not sure what the exact processes or procedures are for creating a release of NATS Server or NATS CLI, but it is my opinion that any distribution avenue (Chocolatey, Scoop, Docker, etc.) detailed in the installation docs should be maintened by the NATS team, and updated as part of the release process. I know that this may not be the best place to discuss this point, but this seemed to be the only repo with overlap between docs, server, and CLI.

**Comment by alexbozhenko** [comment]
@mesakomarevich Thank you so much for reporting it! And apologies it took loooong time to fix.
