### ISSUE TITLE
Broken links in jetstream/streams page

### ISSUE THREAD

**Issue by mprimi** [nats-io/nats.docs#599]
There are some broken links in [this page](https://docs.nats.io/nats-concepts/jetstream/streams)

Example, the two below linking to `/running-a-nats-service/nats_admin/jetstream_admin/replication#...`.

I double-checked the paths and they seem correct, sorry for not submitting a PR/fix directly, but I don't know why they're not currently linking correctly.

```
| [Mirror](#mirror)             | If set, indicates this stream is a mirror of another stream. See [mirrors](/running-a-nats-service/nats_admin/jetstream_admin/replication#mirrors).                                               | 2.2.0   | No (if defined) |
| [Sources](#sources)           | If defined, declares one or more streams this stream will source messages from. See [sources](/running-a-nats-service/nats_admin/jetstream_admin/replication#sources).                            | 2.2.0   | Yes             |

```

**Comment by gcolliso** [comment]
fixed in PR #600
