### ISSUE TITLE
Helm config examples are mostly wrong after 1.0 release

### ISSUE THREAD

**Issue by dylanratcliffe** [nats-io/nats.docs#606]
In this page: https://github.com/nats-io/nats.docs/blob/master/running-a-nats-service/nats-on-kubernetes/helm-charts.md

We give a number of examples of how to set lots of nats config, this is great. The problem is that now that the helm chart has reached 1.0.0, many if not all of them are wrong. e.g. logging

Current:

```yaml
nats:
  logging:
    debug:
    trace:
    logtime:
    connectErrorReports:
    reconnectErrorReports:
```

Correct:

```yaml
config:
  merge:
    debug: true
    trace: true
    # I have no idea how to set connectErrorReports, logtime
    # or reconnectErrorReports. Maybe the same as this? Maybe not?
```

**Comment by gcolliso** [comment]
@dylanratcliffe we are aware that the helm chart section needs to be updated and are working on it. Thank you. If you need assistance before then please ping us in Slack - slack.nats.io

cc/ @bruth

**Comment by bruth** [comment]
Thanks for the heads up @dylanratcliffe. The update will be coming today or tomorrow. In the meantime, check out Artifact Hub: https://artifacthub.io/packages/helm/nats/nats

**Comment by bruth** [comment]
The docs page have been updated to note this. https://docs.nats.io/running-a-nats-service/nats-kubernetes. The other stale pages have been removed to avoid confusion.
