### ISSUE TITLE
Image with hard to read text

### ISSUE THREAD

**Issue by Zambito1** [nats-io/nats.docs#679]
https://github.com/nats-io/nats.docs/blob/60b2ca6785808b6b63c77434fa517bed78f3b37e/running-a-nats-service/configuration/securing_nats/auth_callout.md?plain=1#L9

This image is transparent with gray text that is almost the exact same color as the background of the dark site.

![image](https://github.com/nats-io/nats.docs/assets/7004857/b91d7ccc-9497-40d3-a464-1f5aec880352)

![image](https://github.com/nats-io/nats.docs/assets/7004857/ec324db4-9490-4a02-9a66-a83a545f4fde)

**Comment by gcolliso** [comment]
Thank you for the notification @Zambito1. The image has been replaced with a white background.
