### ISSUE TITLE
Clustering guide is not clear

### ISSUE THREAD

**Issue by m3dbedb** [nats-io/nats.docs#730]
There are too many ports configured in page https://github.com/nats-io/nats.docs/blob/master/running-a-nats-service/configuration/clustering/README.md

```
Server A - the 'seed server'

nats-server -p 4222 -cluster nats://localhost:4248 --cluster_name test-cluster

Server B

nats-server -p 5222 -cluster nats://localhost:5248 -routes nats://localhost:4248 --cluster_name test-cluster

Check the output of the server for the selected client and route ports.

Server C

nats-server -p 6222 -cluster nats://localhost:6248 -routes nats://localhost:4248 --cluster_name test-cluster

Check the output of the server for the selected client and route ports.
```
I suppose one server to have 1 port. So three servers is 3 ports. Why there are 6 ports in quoted text?

**Comment by m3dbedb** [comment]
I have answer:
`Typically only one instance of the server will run per machine, so you can reuse the client port (4222) and the cluster port (4248), and simply the route to the host/port of the seed server.`

**Comment by m3dbedb** [comment]
Here is my working configuration:
```
server_name: nats1
port: 4222
cluster {
  name: test-nats
  port: 6222
  routes: [
    nats-route://192.168.0.20:6222
    nats-route://192.168.0.30:6222
  ]
}
```

```
server_name: nats2
port: 4222
cluster {
  name: test-nats
  port: 6222
  routes: [
    nats-route://192.168.0.10:6222
    nats-route://192.168.0.30:6222
  ]
}
```

```
server_name: nats3
port: 4222
cluster {
  name: test-nats
  port: 6222
  routes: [
    nats-route://192.168.0.10:6222
    nats-route://192.168.0.20:6222
  ]
}
```

**Comment by BlackBooth** [comment]
> There are too many ports configured in page https://github.com/nats-io/nats.docs/blob/master/running-a-nats-service/configuration/clustering/README.md
> 
> ```
> Server A - the 'seed server'
> 
> nats-server -p 4222 -cluster nats://localhost:4248 --cluster_name test-cluster
> 
> Server B
> 
> nats-server -p 5222 -cluster nats://localhost:5248 -routes nats://localhost:4248 --cluster_name test-cluster
> 
> Check the output of the server for the selected client and route ports.
> 
> Server C
> 
> nats-server -p 6222 -cluster nats://localhost:6248 -routes nats://localhost:4248 --cluster_name test-cluster
> 
> Check the output of the server for the selected client and route ports.
> ```
> 
> I suppose one server to have 1 port. So three servers is 3 ports. Why there are 6 ports in quoted text?

You skipped one important line when quoting the docs:

`Here is a simple cluster running on the same machine: `

So when you want to run the mentioned clustering example on the same machine you need the different ports for each nats instance. Your configuration is fine when you have three distinct servers.
