### ISSUE TITLE
Broken Table Markdown

### ISSUE THREAD

**Issue by acornforth** [nats-io/nats.docs#744]
at https://docs.nats.io/running-a-nats-service/configuration/clustering/cluster_config

the table syntax is broken by a newline.

I'm sure sure on the etiquette as i have not contributed to any nats-io projects yet, but i have a PR that fixes this ready to go in a fork.

Should i open the PR against master branch or is there a better target branch for this fix?

**Comment by acornforth** [comment]
https://github.com/nats-io/nats.docs/compare/master...acornforth:nats.docs:patch-1

**Comment by gcolliso** [comment]
Hello @acornforth! You are welcome to submit the PR - thanks!

**Comment by acornforth** [comment]
@gcolliso here you go: https://github.com/nats-io/nats.docs/pull/745
