### ISSUE TITLE
Documentation: link to nats-cli tool is outdated

### ISSUE THREAD

**Issue by katevi** [nats-io/nats.docs#762]
Hi!
It looks like link in the following docs section https://docs.nats.io/using-nats/developer/connecting/userpass
"You can encrypt passwords to pass to nats-server using a simple [tool](https://github.com/nats-io/nats.docs/blob/master/using-nats/nats-tools/nats_cli/README.md):" is outdated -- this https://github.com/nats-io/nats.docs/blob/master/using-nats/nats-tools/nats_cli/readme.md should be used.

**Comment by gcolliso** [comment]
Thanks @katevi
