### ISSUE TITLE
`yay` is not a Linux package manager

### ISSUE THREAD

**Issue by osalbahr** [nats-io/nats.docs#767]
The following [Quick Start](https://docs.nats.io/running-a-nats-service/introduction/installation) section needs to be rewrittern:

https://github.com/nats-io/nats.docs/blob/b016384c9e21d02485a3bcc100978a7efc58aeaf/running-a-nats-service/installation.md?plain=1#L130-L134

Since [Yay](https://github.com/Jguer/yay) is only one choice for an [AUR helper](https://wiki.archlinux.org/title/AUR_helpers) for Arch Linux.

**Comment by FBIGlowie** [comment]
yay!

**Comment by alexbozhenko** [comment]
Thanks for bringing this up! Note was added to: https://docs.nats.io/running-a-nats-service/introduction/installation#installing-via-a-package-manager
