### ISSUE TITLE
Monitoring specs

### ISSUE THREAD

**Issue by SiddiqueAhmad** [nats-io/nats.docs#90]
things are working as said in docs, except the monitoring specs

command line param work but not configuration file param not work or it is not correct, i tried http_port and http both

[https://github.com/nats-io/nats.docs/blob/master/nats-streaming-concepts/monitoring/README.md](url)

**Comment by bruth** [comment]
Hi @SiddiqueAhmad, this is a very old issue, but I did just confirm this works (may have been addressed in the meantime). You may be aware, but note that NATS Streaming has been deprecated and all bug fixes and security patches will stop as of June 1, 2023.
